"""table discounts

Revision ID: 9971de63cd64
Revises: 
Create Date: 2019-09-28 20:11:47.344098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9971de63cd64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('sku_id', sa.String(length=64), nullable=True),
    sa.Column('discounted_sku_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_sku_id'), 'discount', ['sku_id'], unique=True)
    op.create_index(op.f('ix_discount_timestamp'), 'discount', ['timestamp'], unique=False)
    op.create_index(op.f('ix_discount_transaction_id'), 'discount', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discount_transaction_id'), table_name='discount')
    op.drop_index(op.f('ix_discount_timestamp'), table_name='discount')
    op.drop_index(op.f('ix_discount_sku_id'), table_name='discount')
    op.drop_table('discount')
    # ### end Alembic commands ###
